inferenceExtension:
  replicas: 1
  image:
    name: llm-d-inference-scheduler
    hub: ghcr.io/llm-d
    tag: v0.3.1-rc.1
    pullPolicy: Always
  extProcPort: 9002
  pluginsConfigFile: "pd-config.yaml"
  pluginsCustomConfig: # THIS CONFIG NEEDS TO BE CHECKED FOR INF SCHEDULER NEW IMAGE
    pd-config.yaml: |
      # ALWAYS DO PD IN THIS EXAMPLE (THRESHOLD 0)
      apiVersion: inference.networking.x-k8s.io/v1alpha1
      kind: EndpointPickerConfig
      plugins:
      - type: prefill-header-handler
      - type: prefill-filter
      - type: decode-filter
      - type: max-score-picker
      - type: queue-scorer
        parameters:
          hashBlockSize: 5
          maxPrefixBlocksToMatch: 256
          lruCapacityPerServer: 31250
      - type: pd-profile-handler
        parameters:
          threshold: 0
          hashBlockSize: 5
      schedulingProfiles:
      - name: prefill
        plugins:
        - pluginRef: prefill-filter
        - pluginRef: queue-scorer
          weight: 1.0
        - pluginRef: max-score-picker
      - name: decode
        plugins:
        - pluginRef: decode-filter
        - pluginRef: queue-scorer
          weight: 1.0
        - pluginRef: max-score-picker
inferencePool:
  apiVersion: inference.networking.x-k8s.io/v1alpha2 # use old API version for inference
  targetPortNumber: 8000
  modelServerType: vllm
  modelServers:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: ms-pd-llm-d-modelservice
