#!/usr/bin/env sh

# -*- indent-tabs-mode: nil; tab-width: 2; sh-indentation: 2; -*-

# Script used as a readinessProbe to ensure the `cufile.json` exists

set -eu
TARGET="${1:-/etc/cufile.json}"
if [ -e "$TARGET" ]; then
  # Other verification on cufile.json goes here
  exit 0
else
  echo "Missing: $TARGET" >&2
  exit 1
fi
