# This values.yaml file creates the resources for Qwen/Qwen3-0.6B
multinode: false

modelArtifacts:
  uri: "hf://meta-llama/Llama-3.1-70B-Instruct"
  size: 160Gi
  authSecretName: "llm-d-hf-token"
  name: meta-llama/Llama-3.1-70B

routing:
  servicePort: 8000
  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.3.0
    connector: nixlv2
    secure: false

  inferencePool:
    create: false

  httpRoute:
    create: false

  epp:
    create: false

accelerator:
  type: google

decode:
  parallelism:
    tensor: 8
  create: true
  replicas: 2
  extraConfig:
    nodeSelector:
      cloud.google.com/gke-tpu-topology: "2x4"
      cloud.google.com/gke-tpu-accelerator: "tpu-v6e-slice"
  monitoring:
    podmonitor:
      enabled: true
      portName: "metrics"  # decode vLLM service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
  - name: "vllm"
    image: "vllm/vllm-tpu:e92694b6fe264a85371317295bca6643508034ef"
    modelCommand: vllmServe
    args:
      - "--tensor-parallel-size=8"
      - "--max-model-len=4096"
    ports:
      - containerPort: 5557
        protocol: TCP
      - containerPort: 8200
        name: metrics
        protocol: TCP
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    - name: torch-compile-cache
      mountPath: /.cache
  volumes:
  - name: metrics-volume
    emptyDir: {}
  - name: torch-compile-cache
    emptyDir: {}
prefill:
  create: false
